language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"

before_install: sudo apt-get install libbluetooth-dev
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt
# command to run tests, e.g. python setup.py test
script: nosetests --cover-branches --with-coverage --cover-erase --cover-package=obdlib
# Coveralls statistics
after_success: coveralls
